/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.graph.socialnetworkgraphanalyzer.ui;
import com.graph.socialnetworkgraphanalyzer.basicdatastructures.*;

/**
 *
 * @author rafaelc3127
 */
public class InfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
        
        // --------------- INITIALIZE LISTS VALUES --------------- //
        usersList.setListData(new String[0]);
        relationsList.setListData(new String[0]);
        
        // --------------- ADD SPACE BETWEEN ELEMENTS --------------- //
        this.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.insets = new java.awt.Insets(10, 10, 5, 10);
        
        // Add title
        gbc.gridy = 0;
        gbc.weighty = 0;
        this.add(titleLabel, gbc);
        
        // Add users count label
        gbc.gridy = 1;
        this.add(userCountLabel, gbc);
        
        // Add users list
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        this.add(usersListScrollPane, gbc);
        
        // Add relations count label
        gbc.gridy = 3;
        gbc.weighty = 0;
        this.add(relationsCountLabel, gbc);
        
        // Add relations list
        gbc.gridy = 4;
        gbc.weighty = 1.0;
        this.add(relationsListScrollPane, gbc);
        
    }
    
    public void updateGraphInfo(Graph<String> graph) {
        // Update users
        LinkedList<String> nodes = graph.getNodes();
        String[] usersArray = new String[nodes.getSize()];
        Node<String> current = nodes.getHead();
        int index = 0;
        
        while (current != null) {
            usersArray[index] = current.getData();
            current = current.getNext();
            index++;
        }
        
        usersList.setListData(usersArray);
        userCountLabel.setText("Usuarios (" + nodes.getSize() + "):");
        
        // Update relations
        LinkedList<Edge<String>> edges = graph.getEdges();
        String[] relationsArray = new String[edges.getSize()];
        Node<Edge<String>> edgeCurrent = edges.getHead();
        index = 0;
        
        while (edgeCurrent != null) {
            Edge<String> edge = edgeCurrent.getData();
            relationsArray[index] = edge.from + " → " + edge.to;
            edgeCurrent = edgeCurrent.getNext();
            index++;
        }
        
        relationsList.setListData(relationsArray);
        relationsCountLabel.setText("Relaciones (" + edges.getSize() + "):");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLabel = new javax.swing.JLabel();
        userCountLabel = new javax.swing.JLabel();
        usersListScrollPane = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        relationsCountLabel = new javax.swing.JLabel();
        relationsListScrollPane = new javax.swing.JScrollPane();
        relationsList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(300, 700));
        setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(59, 169, 156));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Informacion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 197;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        add(titleLabel, gridBagConstraints);

        userCountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        userCountLabel.setText("Usuarios (0)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        add(userCountLabel, gridBagConstraints);

        usersListScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        usersListScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usersListScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        usersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        usersListScrollPane.setViewportView(usersList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 269;
        gridBagConstraints.ipady = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        add(usersListScrollPane, gridBagConstraints);

        relationsCountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        relationsCountLabel.setText("Relaciones (0)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        add(relationsCountLabel, gridBagConstraints);

        relationsListScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        relationsListScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        relationsListScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        relationsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        relationsListScrollPane.setViewportView(relationsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 269;
        gridBagConstraints.ipady = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 269, 0);
        add(relationsListScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel relationsCountLabel;
    private javax.swing.JList<String> relationsList;
    private javax.swing.JScrollPane relationsListScrollPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userCountLabel;
    private javax.swing.JList<String> usersList;
    private javax.swing.JScrollPane usersListScrollPane;
    // End of variables declaration//GEN-END:variables
}
