/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.graph.socialnetworkgraphanalyzer.ui;

import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author rafaelc3127
 */
public class VisualizationPanel extends javax.swing.JPanel {
    
    private Graph graphStreamGraph;
    private Viewer viewer;

    /**
     * Creates new form VisualizationPanel
     */
    public VisualizationPanel() {
        initComponents();
        setUpGraph();
    }
    
    private void setUpGraph() {
        setLayout(new BorderLayout());
        
        // Create empty GraphStream graph
        graphStreamGraph = new SingleGraph("Red social");
        
        // Configure viewer
        viewer = new SwingViewer(graphStreamGraph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        
        // Get view component and add to panel
        View view = viewer.addDefaultView(false);
        add((Component) view, BorderLayout.CENTER);
    }
    
    public void rebuildGraph(com.graph.socialnetworkgraphanalyzer.basicdatastructures.Graph<String> customGraph) {
        GraphVisualizer.buildCompleteGraph(graphStreamGraph, customGraph);
    }
    
    public void addNode(String username) {
        GraphVisualizer.addNode(graphStreamGraph, username);
    }
    
    public void removeNode(String username) {
        GraphVisualizer.removeNode(graphStreamGraph, username);
    }
    
    public void addEdge(String from, String to) {
        GraphVisualizer.addEdge(graphStreamGraph, from, to);
    }
    
    public void removeEdge(String from, String to) {
        GraphVisualizer.removeEdge(graphStreamGraph, from, to);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
